# serverless.yml

service: myRepNIService

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1

functions:
  app:
    handler: build/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.myrepni.com
    certificateName: 'myrepni.com'
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
